"""The publication order: nothing public happens before everything checkable passed.

Order is the contract: sdist verified, commit, push main, CI green on that
commit, and only then the tag. Dry-run prints the very same steps.
"""

from __future__ import annotations

import contextlib
import io
import os
import tarfile
import tempfile
import unittest
from collections.abc import Callable
from pathlib import Path

from modules.engine.application.ports import ReleasePorts
from modules.engine.application.producer import ProducerRelease
from modules.engine.domain.models import CommandFailed, ReleaseError
from modules.engine.infrastructure.manifest import load_manifest
from tests.test_gates import _sdist_bytes
from tests.test_producer import FakeGit, FakeGitHub, FakeHasher, FakeProcess

TAP_ROOT = Path(__file__).resolve().parents[1]
VERSION = "0.1.8"
HEAD = "c" * 40


class Events:
    """One ordered log shared by the process and git fakes."""

    def __init__(self) -> None:
        self.entries: list[str] = []

    def index(self, prefix: str) -> int:
        for position, entry in enumerate(self.entries):
            if entry.startswith(prefix):
                return position
        raise AssertionError(f"no event starting with {prefix!r}: {self.entries}")

    def has(self, prefix: str) -> bool:
        return any(entry.startswith(prefix) for entry in self.entries)


class PublishingProcess(FakeProcess):
    def __init__(
        self,
        events: Events,
        *,
        ci_failure: bool = False,
        sdist: Callable[[], bytes] = lambda: _sdist_bytes(VERSION),
    ) -> None:
        super().__init__(f"sive {VERSION}")
        self.events = events
        self.ci_failure = ci_failure
        self.sdist = sdist

    def run(
        self,
        args: list[str],
        *,
        cwd: Path,
        capture: bool = False,
        timeout_seconds: float | None = None,
    ) -> str:
        self.events.entries.append(" ".join(args))
        if args[:3] == ["uv", "build", "--sdist"]:
            out = Path(args[args.index("--out-dir") + 1])
            (out / f"sive-{VERSION}.tar.gz").write_bytes(self.sdist())
        if args[:3] == ["gh", "run", "watch"] and self.ci_failure:
            raise CommandFailed("gh run watch --exit-status")
        return self.version_output if capture else ""

    def try_run(self, args: list[str], *, cwd: Path) -> tuple[int, str]:
        self.events.entries.append(" ".join(args))
        if args[:3] == ["gh", "run", "list"]:
            return 0, '[{"databaseId": 42}]'
        return 0, ""


class PublishingGit(FakeGit):
    def __init__(self, events: Events, *, already_committed: bool = False) -> None:
        super().__init__()
        self.events = events
        self.already_committed = already_committed

    def run(self, args: list[str], *, cwd: Path) -> None:
        self.events.entries.append("git " + " ".join(args))

    def output(self, args: list[str], *, cwd: Path) -> str:
        self.events.entries.append("git " + " ".join(args))
        if args[:2] == ["diff", "--cached"]:
            return "" if self.already_committed else "pyproject.toml\nuv.lock"
        return HEAD


class RecordingGitHub(FakeGitHub):
    """Keeps what each created release was given as its body."""

    def __init__(self) -> None:
        self.bodies: list[str] = []

    def create_release(
        self, repository: str, tag: str, asset: Path, title: str, notes: str
    ) -> None:
        self.bodies.append(notes)


def _release(
    root: Path,
    process: PublishingProcess,
    git: PublishingGit,
    github: FakeGitHub | None = None,
) -> ProducerRelease:
    (root / "pyproject.toml").write_text(
        f'[project]\nname = "sive"\nversion = "{VERSION}"\n'
    )
    (root / "uv.lock").write_text(
        f'[[package]]\nname = "sive"\nversion = "{VERSION}"\n'
    )
    return ProducerRelease(
        load_manifest(TAP_ROOT, "sive"),
        root,
        ReleasePorts(process, git, github or FakeGitHub(), FakeHasher()),
    )


REVIEWED_CHANGELOG = f"""# Changelog

All notable changes to this project will be documented in this file.

## [{VERSION}] - 2026-10-10

### Fixed

- Stop the hook re-entering itself

## [0.1.7] - 2026-09-01

### Added

- An older entry

[{VERSION}]: https://example.invalid/compare/sive-0.1.7...sive-{VERSION}
[0.1.7]: https://example.invalid/compare/sive-0.1.6...sive-0.1.7

<!-- generated by git-cliff -->
"""


class ReleaseBodyTests(unittest.TestCase):
    def _publish(self, changelog: str | None) -> RecordingGitHub:
        events, github = Events(), RecordingGitHub()
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "dist").mkdir()
            if changelog is not None:
                (root / "CHANGELOG.md").write_text(changelog)
            release = _release(
                root, PublishingProcess(events), PublishingGit(events), github
            )
            release.build_release(VERSION, HEAD, dry_run=False)
        return github

    def test_the_release_body_is_the_reviewed_section_for_the_version(self) -> None:
        github = self._publish(REVIEWED_CHANGELOG)

        self.assertEqual(
            github.bodies,
            [
                (
                    f"## [{VERSION}] - 2026-10-10\n\n### Fixed\n\n"
                    "- Stop the hook re-entering itself"
                )
            ],
        )

    def test_an_older_release_section_is_not_published_by_mistake(self) -> None:
        github = self._publish(REVIEWED_CHANGELOG)

        self.assertNotIn("An older entry", github.bodies[0])

    def test_a_changelog_without_the_version_cannot_be_published(self) -> None:
        with self.assertRaisesRegex(ReleaseError, f"no section for {VERSION}"):
            self._publish(REVIEWED_CHANGELOG.replace(f"## [{VERSION}]", "## [9.9.9]"))

    def test_a_missing_changelog_cannot_be_published(self) -> None:
        with self.assertRaisesRegex(ReleaseError, "CHANGELOG.md"):
            self._publish(None)


class PublicationOrderTests(unittest.TestCase):
    def _run(
        self,
        *,
        ci_failure: bool = False,
        already_committed: bool = False,
    ) -> tuple[Events, ProducerRelease]:
        events = Events()
        process = PublishingProcess(events, ci_failure=ci_failure)
        git = PublishingGit(events, already_committed=already_committed)
        with tempfile.TemporaryDirectory() as tmp:
            release = _release(Path(tmp), process, git)
            with contextlib.suppress(ReleaseError):
                release.commit_tag_push(VERSION, dry_run=False)
        return events, release

    def test_everything_checkable_passes_before_anything_is_tagged(self) -> None:
        events, release = self._run()
        tag = release.manifest.tag(VERSION)

        order = [
            events.index("uv build --sdist"),
            events.index("git commit"),
            events.index("git push origin main"),
            events.index("gh run watch"),
            events.index("git tag -a"),
            events.index(f"git push origin {tag}"),
        ]
        self.assertEqual(order, sorted(order), f"out of order: {events.entries}")

    def test_the_tag_is_never_pushed_together_with_main(self) -> None:
        events, release = self._run()
        tag = release.manifest.tag(VERSION)

        self.assertFalse(events.has(f"git push origin main {tag}"))

    def test_ci_is_awaited_for_each_required_workflow_on_the_pushed_commit(
        self,
    ) -> None:
        events, _ = self._run()
        listings = [e for e in events.entries if e.startswith("gh run list")]

        self.assertEqual(len(listings), 2)
        for listing, workflow in zip(
            listings, ("tests.yml", "quality.yml"), strict=True
        ):
            self.assertIn(f"--workflow {workflow}", listing)
            self.assertIn(f"--commit {HEAD}", listing)

    def test_commit_stages_the_workspace_lockfile(self) -> None:
        """The single lock lives at the workspace root, not beside the package."""
        events = Events()
        with tempfile.TemporaryDirectory() as tmp:
            workspace = Path(tmp)
            (workspace / "uv.lock").write_text(
                f'[[package]]\nname = "sive"\nversion = "{VERSION}"\n'
            )
            member = workspace / "packages" / "sive"
            member.mkdir(parents=True)
            (member / "pyproject.toml").write_text(
                f'[project]\nname = "sive"\nversion = "{VERSION}"\n'
            )
            release = ProducerRelease(
                load_manifest(TAP_ROOT, "sive"),
                member,
                ReleasePorts(
                    PublishingProcess(events),
                    PublishingGit(events),
                    FakeGitHub(),
                    FakeHasher(),
                ),
            )
            release.commit_tag_push(VERSION, dry_run=False)

        expected_lock = os.path.relpath(workspace / "uv.lock", member)
        self.assertTrue(events.has(f"git add pyproject.toml {expected_lock}"))

    def test_the_prepare_commit_carries_the_reviewed_notes(self) -> None:
        """The version bump and its reviewed CHANGELOG.md are one commit."""
        events = Events()
        with tempfile.TemporaryDirectory() as tmp:
            release = _release(
                Path(tmp), PublishingProcess(events), PublishingGit(events)
            )
            release.commit_tag_push(VERSION, dry_run=False)

        self.assertTrue(events.has("git add pyproject.toml uv.lock CHANGELOG.md"))

    def test_failing_ci_leaves_no_tag_locally_or_on_the_remote(self) -> None:
        events, _ = self._run(ci_failure=True)

        self.assertTrue(events.has("git push origin main"))
        self.assertFalse(events.has("git tag"))
        self.assertFalse(events.has("git push origin sive-"))

    def test_an_invalid_sdist_changes_nothing(self) -> None:
        events = Events()
        process = PublishingProcess(events, sdist=lambda: b"not a tarball")
        with tempfile.TemporaryDirectory() as tmp:
            release = _release(Path(tmp), process, PublishingGit(events))
            with self.assertRaises(tarfile.TarError):
                release.commit_tag_push(VERSION, dry_run=False)

        for mutation in ("git add", "git commit", "git push", "git tag"):
            self.assertFalse(events.has(mutation), f"{mutation} ran: {events.entries}")

    def test_a_retry_does_not_fail_when_the_prepare_commit_already_exists(
        self,
    ) -> None:
        events, _ = self._run(already_committed=True)

        self.assertFalse(events.has("git commit"))
        self.assertTrue(events.has("git tag -a"))

    def test_dry_run_prints_the_same_steps_in_the_same_order(self) -> None:
        events = Events()
        with tempfile.TemporaryDirectory() as tmp:
            release = _release(
                Path(tmp), PublishingProcess(events), PublishingGit(events)
            )
            printed = io.StringIO()
            with contextlib.redirect_stdout(printed):
                release.commit_tag_push(VERSION, dry_run=True)

            steps = [step.label for step in release.publication_steps(VERSION)]
        lines = [
            line.removeprefix("[dry-run] ")
            for line in printed.getvalue().splitlines()
            if line.startswith("[dry-run] ")
        ]
        self.assertEqual(lines, steps)
        self.assertFalse(events.has("git push"), "dry-run pushed")


if __name__ == "__main__":
    unittest.main()
