# frozen_string_literal: true

cask "hyprspace" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version "0.3.0"
  sha256 "bb66e3ac62505bbadbe281bb4e3a2d0632394bcdff7a1b8f28c672371952fcc6"

  url "https://github.com/PeachlifeAB/hyprspace-releases/releases/download/v#{version}/Hyprspace-v#{version}.zip"
  name "Hyprspace"
  desc "Tiling window manager based on AeroSpace"
  homepage "https://hyprspace.net/"

  # hyprspace-releases carries only this product, so its single latest
  # release is the right answer -- unlike the tap's formulae, which share
  # one repository under <product>- tag prefixes.
  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on formula: "gum"
  depends_on macos: :sequoia

  app "Hyprspace-v#{version}/Hyprspace.app"
  binary "Hyprspace-v#{version}/bin/hyprspace"
  binary "Hyprspace-v#{version}/shell-completion/zsh/_hyprspace",
         target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_hyprspace"
  binary "Hyprspace-v#{version}/shell-completion/bash/hyprspace",
         target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/hyprspace"
  binary "Hyprspace-v#{version}/shell-completion/fish/hyprspace.fish",
         target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/hyprspace.fish"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/Hyprspace.app"], must_succeed: false
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/Hyprspace-v#{version}/bin/hyprspace", "{{staged_path}}/Hyprspace-v#{version}/libexec"], must_succeed: false

    mkdir_p ".config/hyprspace/docs", base: "home"
    copy "Hyprspace-v#{version}/artifacts/configs/docs/README.md",
         ".config/hyprspace/docs/README.md",
         source_base: "staged_path", target_base: "home"
    copy "Hyprspace-v#{version}/artifacts/configs/docs/ACKNOWLEDGMENTS.md",
         ".config/hyprspace/docs/ACKNOWLEDGMENTS.md",
         source_base: "staged_path", target_base: "home"
    if_path_exists "Hyprspace-v#{version}/AeroSpace/docs/config-examples/config.default.toml", base: "staged_path" do
      copy "Hyprspace-v#{version}/AeroSpace/docs/config-examples/config.default.toml",
           ".config/hyprspace/docs/default-config.toml",
           source_base: "staged_path", target_base: "home"
    end
  end

  # Only what this cask creates outside its own artifacts: the docs the
  # flight block copies, and the app's preferences. NOT ~/.config/hyprspace
  # itself -- that holds the user's own config.toml, and is often a git
  # repository. zap runs only on `brew uninstall --zap`.
  zap trash: [
    "~/.config/hyprspace/docs",
    "~/Library/Preferences/peachlife.hyprspace.plist",
    "~/Library/Saved Application State/peachlife.hyprspace.savedState",
  ]

  caveats do
    <<~EOS
      Run 'hyprspace init' to start the setup wizard.
      Hyprspace.app was installed to /Applications.
    EOS
  end

  Dir["#{staged_path}/Hyprspace-v#{version}/manpage/*"].each { |man| manpage man }
end
