# frozen_string_literal: true

cask "hyprspace" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version "0.1.9"
  sha256 "3a3e7cbb669c14de10461c55ebd69dcddb9c229a131385706c374958d34f9522"

  url "https://github.com/PeachlifeAB/hyprspace-releases/releases/download/v#{version}/Hyprspace-v#{version}.zip",
      verified: "github.com/PeachlifeAB/hyprspace-releases/"
  name "Hyprspace"
  desc "Tiling window manager based on AeroSpace"
  homepage "https://hyprspace.net/"

  depends_on macos: ">= :sequoia" # macOS 15
  depends_on formula: "gum"

  app "Hyprspace-v#{version}/Hyprspace.app"
  binary "Hyprspace-v#{version}/bin/hyprspace"
  binary "Hyprspace-v#{version}/shell-completion/zsh/_hyprspace",
         target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_hyprspace"
  binary "Hyprspace-v#{version}/shell-completion/bash/hyprspace",
         target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/hyprspace"
  binary "Hyprspace-v#{version}/shell-completion/fish/hyprspace.fish",
         target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/hyprspace.fish"

  postflight do
    system "/bin/sh", "-c", "xattr -dr com.apple.quarantine '#{appdir}/Hyprspace.app' 2>/dev/null || true"
    system "/bin/sh", "-c", "xattr -dr com.apple.quarantine '#{staged_path}/Hyprspace-v#{version}/bin/hyprspace' '#{staged_path}/Hyprspace-v#{version}/libexec' 2>/dev/null || true"
    system "/bin/sh", "-c", "mkdir -p ~/.config/hyprspace/docs && cp '#{staged_path}/Hyprspace-v#{version}/artifacts/configs/docs/README.md' '#{staged_path}/Hyprspace-v#{version}/artifacts/configs/docs/ACKNOWLEDGMENTS.md' ~/.config/hyprspace/docs/ && cp '#{staged_path}/Hyprspace-v#{version}/AeroSpace/docs/config-examples/config.default.toml' ~/.config/hyprspace/docs/default-config.toml 2>/dev/null || true"
  end

  caveats do
    <<~EOS
      Run 'hyprspace init' to start the setup wizard.
      Hyprspace.app was installed to /Applications.
    EOS
  end

  Dir["#{staged_path}/Hyprspace-v#{version}/manpage/*"].each { |man| manpage man }
end
