schema_version = 1
kind = "cask"
name = "hyprspace"
repository = "PeachlifeAB/hyprspace-releases"
cask = "hyprspace"
release_notes_template = "https://github.com/PeachlifeAB/hyprspace-releases/releases/tag/v{version}"
